apiVersion: v1
kind: Service
metadata:
  name: weather-app
spec:
  selector:
    app: weather-app  
  ports:
  - name: http
    port: 5000
    targetPort: http-web-svc
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-app
spec:
  selector:
    matchLabels:
      app: weather-app
  replicas: 2
  template:
    metadata:
      labels:
        app: weather-app
    spec:
      containers:
        - name: weather-app
          image: weather-app:latest
          imagePullPolicy: Never
          ports:
          - containerPort: 5000
            name: http-web-svc

